// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3X4G8aS4aCcgO6Ovi5ldYnnEsXABte3Q',
    appId: '1:565227222478:web:4aa117646ea94f6f8ca79f',
    messagingSenderId: '565227222478',
    projectId: 'peachpulse-ddebd',
    authDomain: 'peachpulse-ddebd.firebaseapp.com',
    storageBucket: 'peachpulse-ddebd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkS8hNheJmE_Dpvf8jLktTNG2GQ7jsSg',
    appId: '1:565227222478:android:b602b58215f9f7608ca79f',
    messagingSenderId: '565227222478',
    projectId: 'peachpulse-ddebd',
    storageBucket: 'peachpulse-ddebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChlz7m8GVHyxogWXwyg76-iiIVKMDgAyE',
    appId: '1:565227222478:ios:7fcdced6a060b1938ca79f',
    messagingSenderId: '565227222478',
    projectId: 'peachpulse-ddebd',
    storageBucket: 'peachpulse-ddebd.firebasestorage.app',
    iosBundleId: 'com.example.peachPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChlz7m8GVHyxogWXwyg76-iiIVKMDgAyE',
    appId: '1:565227222478:ios:7fcdced6a060b1938ca79f',
    messagingSenderId: '565227222478',
    projectId: 'peachpulse-ddebd',
    storageBucket: 'peachpulse-ddebd.firebasestorage.app',
    iosBundleId: 'com.example.peachPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3X4G8aS4aCcgO6Ovi5ldYnnEsXABte3Q',
    appId: '1:565227222478:web:538f763e1d37db0b8ca79f',
    messagingSenderId: '565227222478',
    projectId: 'peachpulse-ddebd',
    authDomain: 'peachpulse-ddebd.firebaseapp.com',
    storageBucket: 'peachpulse-ddebd.firebasestorage.app',
  );
}
